apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ks-backend
  template:
    metadata:
      labels:
        app: ks-backend
    spec:
      containers:
      - name: ks-backend
        image: noahhh117/ks-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000  # 👈 記得與你的 Flask/Gunicorn 監聽埠保持一致